### ISSUE TITLE
No PINE64 kernel config?

### ISSUE THREAD

**Issue by wca** [tomtor/image-freebsd-pine64#1]
The `mkimage.sh` script currently references a PINE64 kernel config file, but this file is not included or described, and not available in FreeBSD's source tree.  Is this meant to be a copy of GENERIC with a different name, or does Pine64 need some special configuration?

**Comment by tomtor** [comment]
FreeBSD is not ported to the Pine yet.

I am working on that in a branch im my github repo but it is 100% untested
because I have no Pine yet. As soon as I have been able to boot a kernel on
my Pine I'll post about it.

Op 20:32 VR 29 Apr 2016 schreef Will Andrews notifications@github.com:

**Comment by hstenn** [comment]
I just got 2 pine64+ boards and I'd love to run FreeBSD on them.  Anything I can do to help?

**Comment by wca** [comment]
There should be FreeBSD pine64 images in the near future.  Several people at BSDCan have been collaborating on this.  Yesterday, my board booted FreeBSD/arm64 to multiuser; sharp edges are being worked out.

**Comment by hstenn** [comment]
That's great news Will, thanks!

H

**Comment by lin7sh** [comment]
This is so awesome!

**Comment by kithrup** [comment]
Any update on this?  Got my Pine64 and don't want to sully it with linux ;).

**Comment by tomtor** [comment]
The PINE64 kernel builds and runs but without any devices yet. :-/

Don't hold your breath. Unless you want to experiment to get some devices
working yourself I suggest using Linux to make use of your Pine.

Note that the rpi3 port is also not available yet.

Op vr 1 jul. 2016 04:58 schreef kithrup notifications@github.com:

**Comment by brd** [comment]
Eh?  What devices are you referring to @tomtor ?

There is a bunch of work happening in this tree: https://github.com/jaredmcneill/freebsd/tree/allwinner-a64

**Comment by tomtor** [comment]
I also have a lot of Pine64 (and Odroid c2) work in

https://github.com/tomtor/freebsd/tree/tc2

but that does not mean that it is ready to use...

Op vr 1 jul. 2016 16:45 schreef Brad Davis notifications@github.com:

**Comment by lin7sh** [comment]
@brd Got my pine64 today and just found out that you are the maintainer of u-boot for pine64 on freshport. Could you write some tutorial for a Newbie like me,

**Comment by hoopty** [comment]
What is the status of arm64 now that FreebSD 11 is released?  I have a Pine64+ and could get the ODROID-C2 if that was a better route to getting an arm64 SoC with FreeBSD.

**Comment by tomtor** [comment]
Hi Bryce,

Even the rpi3 is still not supported for FreeBsd.

I have both an odroid-c2 and pine, but I suggest a 32bit rpi if you really
want FreeBSD.

Tom

Op zo 9 okt. 2016 09:40 schreef Bryce Edwards notifications@github.com:

**Comment by brd** [comment]
Just for reference all the work has been pushed into https://github.com/freebsd/crochet.  That is used to build images for http://www.raspbsd.org for both the RPi3 and Pine64.
